package goss

import (
	"fmt"
	"strings"
	"time"

	"github.com/CosmoLabs-org/cosmo-smoke/internal/schema"
	"gopkg.in/yaml.v3"
)

// EmitMeta holds metadata for the generated output header.
type EmitMeta struct {
	Source    string
	Timestamp time.Time
}

// Stats returns counts of warnings by category.
func Stats(warnings []TranslationWarning) (direct, commandFallback, skipped int) {
	for _, w := range warnings {
		switch w.Category {
		case WarnCommandFallback:
			commandFallback++
		case WarnSkipped:
			skipped++
		case WarnPartial:
			// partial counts as a command fallback for stats
			commandFallback++
		}
	}
	return direct, commandFallback, skipped
}

// Emit generates a .smoke.yaml string from translated tests with comments.
func Emit(tests []schema.Test, warnings []TranslationWarning, meta EmitMeta) (string, error) {
	var b strings.Builder

	// Header
	b.WriteString("# Generated by: smoke migrate goss\n")
	if meta.Source != "" {
		b.WriteString(fmt.Sprintf("# Source: %s\n", meta.Source))
	}
	if !meta.Timestamp.IsZero() {
		b.WriteString(fmt.Sprintf("# Migrated: %s\n", meta.Timestamp.Format(time.RFC3339)))
	}

	_, cmdFallback, skipped := Stats(warnings)
	b.WriteString(fmt.Sprintf("# Stats: %d tests, %d command-fallback, %d TODO\n",
		len(tests), cmdFallback, skipped))
	b.WriteString("\n")

	// Build a lookup for warnings by resource
	warningByResource := make(map[string][]TranslationWarning)
	for _, w := range warnings {
		warningByResource[w.Resource] = append(warningByResource[w.Resource], w)
	}

	// Output config
	cfg := schema.SmokeConfig{
		Tests: tests,
	}

	// Marshal tests to YAML first for structure
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return "", fmt.Errorf("marshaling smoke config: %w", err)
	}

	b.Write(data)

	return b.String(), nil
}

// EmitStats prints a migration stats summary to the provided writer (or returns as string).
func EmitStats(warnings []TranslationWarning) string {
	_, cmdFallback, skipped := Stats(warnings)

	var lines []string
	lines = append(lines, "Migration stats:")
	lines = append(lines, fmt.Sprintf("  Command fallbacks: %d", cmdFallback))
	lines = append(lines, fmt.Sprintf("  Skipped (TODO):    %d", skipped))

	if len(warnings) > 0 {
		lines = append(lines, "")
		lines = append(lines, "Warnings:")
		for _, w := range warnings {
			lines = append(lines, fmt.Sprintf("  [%s] %s: %s", w.GossKey, w.Resource, w.Message))
		}
	}

	return strings.Join(lines, "\n")
}
